#服务器端口
server:
  port: 9101

#数据源配置
spring:
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

# 租户表维护
blade:
  tenant:
    column: tenant_id
    tables:
      - tb_news
      - tb_goods
